apiVersion: v1
kind: Pod
metadata:
  name: nodejs-api
  labels:
    app: nodejs-api
spec:
  containers:
  - name: nodejs-api
    image: sudhan/nodejs-api:latest
#    command: 
#    - sleep 
#    - "12000"
    env:
    - name: MYSQL_HOST
      value: "mysql-service"
    - name: MYSQL_PORT
      value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service
spec:
  type: NodePort
  selector:
    app: nodejs-api
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30020
