apiVersion: v1
kind: Pod
metadata:
  name: nodejs-ui
  labels:
    app: nodejs-ui
spec:
  containers:
  - name: nodejs-ui
    image: sudhan/nodejs-ui:latest
#    imagePullPolicy: Always
    workingDir: /opt/app
    stdin: true 
    tty: true 
#    command: ["/bin/sh","-c", "/opt/app/fix_package.sh && npm start && sleep 12000"]
    command: ["/bin/sh","-c"]
    args:
      - /opt/app/fix_package.sh;
        cat package.json;
        echo starting;
        pwd;
        yarn start;
        echo $?;
        echo completed;
        sleep 12000;
        echo done;
#    command: 
#    - /bin/sh
#    - "runall.sh"
#    command: 
#    - sleep 
#    - "12000"
    env:
    - name: API_SERVER_HOST
      value: "nodejs-api-service"
    - name: API_SERVER_PORT
      value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-ui-service
spec:
  type: NodePort
  selector:
    app: nodejs-ui
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30021
